### ISSUE TITLE
White background in Bulk Edit via Property Matrix

### ISSUE THREAD

**Issue by coden1ke** [hugoattal/DarkerNodes#121]
![UE4Editor_kcpuELMh1X](https://user-images.githubusercontent.com/6880838/105783335-38c85500-5f44-11eb-9091-c86c8ed79274.png)

I do not believe any of my theme settings are affecting the row background color, but just in case here is a screenshot of my settings. 

![image](https://user-images.githubusercontent.com/6880838/105783650-fb17fc00-5f44-11eb-847a-6fe60d14fa7f.png)

**Comment by TheHerobrine** [comment]
@coden1ke Seeing the settings, it seems that you're not using the last version of Darker Nodes (2.5)

In any case, that's probably a place I missed... Could you point me to where I can find that "Bulk Edit via Property Matrix" panel? I'm not familiar with it.

**Comment by coden1ke** [comment]
@TheHerobrine Oh interesting! - Did you push an update sometime today? The Epic Launcher did not prompt me for an update when I started work this morning. 

![image](https://user-images.githubusercontent.com/6880838/105789390-5b606b00-5f50-11eb-8c56-f96ea4b9a1b6.png)

You can access the Property Matrix by Right Clicking on (I believe) any file type > Asset Actions > Bulk Edit via Property Matrix nearing the bottom of the fold out menu.

**Comment by TheHerobrine** [comment]
Fixed! I absolutely didn't know that feature 😅...
![image](https://user-images.githubusercontent.com/4563971/107126806-55547d80-68b2-11eb-94b4-2bdc6c8ee1f2.png)

**Comment by Ares9323** [comment]
> it seems that you're not using the last version of Darker Nodes (2.5)

Hi! I'm using the latest version from the unreal marketplace for UE 4.27, but it says that the version is 1.5 and the property matrix table is not readable:

![image](https://user-images.githubusercontent.com/46932745/204101454-c0832bd7-8380-4660-aeab-6c4e50a48f97.png)

**Comment by Ares9323** [comment]
> This is likely that you have the plugin installed twice

I thought the same, I looked for it inside both folder (Marketplace and Project) but only that 2.6 version was present.
Now I think I discovered the issue: The .uproject file was associated with an old source build of Unreal and I wasn't aware of this...

Now I switched to 4.27.2 and it's working fine:
![image](https://user-images.githubusercontent.com/46932745/204586119-64febfbe-323e-432e-b78f-1ef4e7a48b70.png)

Sorry for wasting your time, have a nice day!

**Comment by Ares9323** [comment]
Sorry to disturb you again for the same issue, I'm still seeing this window white in UE 5.1.1:

![image](https://user-images.githubusercontent.com/46932745/219675101-1377bdff-9528-4e53-b0fd-9bdd107f424c.png)

This time I've double checked that I don't have the plugin installed twice, and I'm using the latest version from the marketplace.
